# Generated by Django 4.2.7 on 2023-11-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_computer', to='products.product')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_printer', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('hd', models.IntegerField()),
                ('cd', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('hd', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('screen', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
